package br.com.mateusparente;
// Generated 05/06/2019 15:12:32 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Exemplo generated by hbm2java
 */
@Entity
@Table(name="EXEMPLO"
    ,schema="MATEUS"
)
public class Exemplo  implements java.io.Serializable {


     private Long id;
     private String descricao;

    public Exemplo() {
    }

    public Exemplo(String descricao) {
       this.descricao = descricao;
    }
   
     @SequenceGenerator(name="br.com.mateusparente.ExemploIdGenerator", sequenceName="MATEUS.SQ_EXEMPLO")@Id @GeneratedValue(strategy=SEQUENCE, generator="br.com.mateusparente.ExemploIdGenerator")

    
    @Column(name="EXM_ID", nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="EXM_DESCRICAO", nullable=false)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


